# Generated by Django 4.2.7 on 2023-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(max_length=45, null=True)),
                ('image', models.CharField(max_length=45, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=45, null=True)),
                ('uploaded_by', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
    ]
