# Generated by Django 4.2.7 on 2023-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, null=True)),
                ('surname', models.CharField(max_length=45, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('weight', models.CharField(max_length=10, null=True)),
                ('height', models.CharField(max_length=10, null=True)),
                ('b_pressure', models.CharField(max_length=10, null=True)),
                ('blood_type', models.CharField(max_length=5, null=True)),
                ('diagnosis', models.TextField(null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=45, null=True)),
                ('uploaded_by', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
    ]
